<?php

/**
 * @file
 * Integrate Drupal with Twitter Bootstrap.
 */

/**
 * Implements hook_library().
 */
function bootstrap_library() {
  $path = libraries_get_path('bootstrap');
  $libraries['bootstrap'] = array(
    'title' => 'Bootstrap, from Twitter',
    'website' => 'http://twitter.github.com/bootstrap/',
    'version' => '2.0.0',
    'js' => array(
      $path . '/js/bootstrap.min.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 2,
      ),
    ),
    'css' => array(
      $path . '/css/bootstrap.min.css' => array(
        'group' => CSS_SYSTEM,
        'weight' => 2,
      ),
    ),
  );
  $libraries['bootstrap-responsive'] = array(
    'title' => 'Bootstrap Responsive',
    'website' => 'http://twitter.github.com/bootstrap/',
    'version' => '2.0.0',
    'css' => array(
      $path . '/css/bootstrap-responsive.min.css' => array(
        'group' => CSS_SYSTEM,
        'weight' => 2,
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_init().
 */
function bootstrap_init() {
  drupal_add_library('bootstrap', 'bootstrap');
  drupal_add_library('bootstrap', 'bootstrap-responsive');
}
